# -*- coding: utf-8 -*-
"""body_fat_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8LzYSHr8hOYzy0ko5kholDuBIVzX-86
"""

import pandas as pd

data = pd.read_csv('/content/bodyfat.csv')

data.head()

X = data.drop('BodyFat' ,axis=1)
Y = data['BodyFat']

X.head()

# spliting the data for traning and testing 
from sklearn.model_selection import train_test_split

X_train , X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=2)

X_train.head()

X.shape

X_test.shape

Y_train.head()

from sklearn.preprocessing import StandardScaler

ss= StandardScaler()
scaled_train= ss.fit_transform(X_train)

from sklearn.neighbors import KNeighborsRegressor
knn= KNeighborsRegressor()
knn.fit(scaled_train,Y_train)
print(knn.score(scaled_train,Y_train))



